### ISSUE TITLE
Display bug of the chord diagram

### ISSUE THREAD

**Issue by AdamW666** [shahinrostami/chord_rs#1]
Dear Shahin,
I bought your book and copy the code to run in Jupyter Lab like this.
![image](https://user-images.githubusercontent.com/53825932/83343261-2fe29d80-a33b-11ea-9eb6-808960335d09.png)

Nothing error happened, but nothing happened. No chart display. 

By the way, your book is coool.

**Comment by shahinrostami** [comment]
Thank you, I hope you're enjoying the book!

I have updated the book (you can download the updated copy) with some corrections and also a whole new section.

The only thing you should need to fix the above is to update the version of the `chord` crate to:

```rust
:dep chord = {Version = "0.1.4"}
```

Please let me know how you get on!

**Comment by AdamW666** [comment]
Yes, the new version works well. Thank you!

**Comment by shahinrostami** [comment]
Happy to hear it @AdamW666 ! 

I hope you like it, and please feel free to share the awesome things you make with the package :)
