### ISSUE TITLE
No example picture in the article; dead link

### ISSUE THREAD

**Issue by vi** [shahinrostami/chord_rs#2]
[The article](https://shahinrostami.com/posts/programming/rust-notebooks/chord-diagrams/) should have some picture of a chord diaram, for example, like in the repository README.

Also ["Example Image"](https://github.com/shahinrostami/chord_rs/blob/master/images/1.gif) link at the bottom on Github repository's README does not work.

**Comment by shahinrostami** [comment]
> [The article](https://shahinrostami.com/posts/programming/rust-notebooks/chord-diagrams/) should have some picture of a chord diaram, for example, like in the repository README.

Do the chord diagrams not appear for you? e.g. <img width="439" alt="Screenshot 2020-06-01 at 13 03 51" src="https://user-images.githubusercontent.com/15690380/83407304-5a4e5c80-a408-11ea-9d98-1486ea7a620c.png">



> Also ["Example Image"](https://github.com/shahinrostami/chord_rs/blob/master/images/1.gif) link at the bottom on Github repository's README does not work.

Thank you - will have a look!

**Comment by vi** [comment]
Indeed, there is interactive diagram. It just requires JavaScript to be enabled for more domains.

Without JS it looks like a normal article, just without any hint of pictures.

**Comment by shahinrostami** [comment]
Added a GIF and a few example images (pinned reddit post screenshot)!
