### ISSUE TITLE
Update required (but no crate update available)

### ISSUE THREAD

**Issue by tommilligan** [shahinrostami/chord_rs#4]
I'm using the v0.1.6 crate, which is the latest available version on [crates.io](https://crates.io/crates/chord)

Today I got the following message in the output file:

![image](https://user-images.githubusercontent.com/12255914/103016328-caa20400-4539-11eb-89cc-62be4d1e34b1.png)

This looks to be because the embedded template URL `https://shahinrostami.com/assets/chord/chord_0_0_12.tmpl` has been updated to show this message.

The Python packages looks to be using a new endpoint, `https://api.shahin.dev/chordfree`, to perform server side rendering (like the pro version always has).

I have a PR that fixes this, I'll send it over now.

**Comment by shahinrostami** [comment]
Hi @tommilligan, thank you for raising this issue otherwise I may not have noticed until after Christmas! It looks like the crate didn't publish properly. I'll get moving on this now and update when it's ready.

**Comment by shahinrostami** [comment]
Thank you @tommilligan - I went with some of your suggestions and also used this opportunity to establish feature parity between the Rust crate and the Python package.

The following features are now available in the Rust crate:

```
    pub verb: String,
    pub symmetric: bool,
    pub title: String,
    pub arc_numbers: bool,
    pub divide_left_label: String,
    pub divide_right_label: String,
    pub inner_radius_scale: f64,
    pub outer_radius_scale: f64,
    pub allow_download: bool,
    pub conjunction: String,
    pub reverse_gradients: bool,
```

I'm here if anything goes wrong.

It was flattering to see this issue raised so soon after the change was made. It's nice to see people using the crate! 

I hope you have a great Christmas!
